### PR TITLE
Migrate to UBI8 base layer

### PR DESCRIPTION
**Pull request by leifmadsen**
Note this work is based upon the existing PR for migrating to GitHub Actions and passing clang linting.

### CODE REVIEW

**Review by pleimer — APPROVED** [review]
thanks for being so quick about this!

**Comment by leifmadsen** [comment]
image

**Comment by leifmadsen** [comment]
Ahhh I guess annocheck isn't available in ubi8. I don't think it's worth trying to figure out what repos might exist that allows for it to be installed on ubi8 when really it's just a build and verify check. I suppose we could try doing that in the future though.

**Comment by leifmadsen** [comment]
Closing this in favour of #18

**Pull request closed without merging**
